#!/usr/bin/env python3
"""
Template Manager for agent file generation.

Provides templates for agent.py and server.py files with placeholders
that can be replaced based on agent configuration.
"""
import os
from typing import Dict, Any

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
AGENTS_DIR = os.path.join(BASE_DIR, 'agents')


def get_agent_template(agent_name: str, session: Dict[str, Any]) -> str:
    """Get the agent.py template with placeholders replaced."""
    with open(os.path.join(AGENTS_DIR, 'general_agent.py'), 'r', encoding='utf-8') as f:
        template = f.read()
    
    class_agent_name = "".join([word.capitalize() for word in agent_name.split("_")]) + "Agent"
    class_server_name = "".join([word.capitalize() for word in agent_name.split("_")]) + "Server"
    
    # Replace placeholders
    template = template.replace('self.agent_id = "general-1"', f'self.agent_id = "{agent_name}-1"')
    template = template.replace('self.service_name = "General Agent"', f'self.service_name = "{session.get("name", agent_name)}"')
    template = template.replace('GeneralAgent', class_agent_name)
    template = template.replace('General Agent', session.get("name", agent_name))
    
    # Fix python path insertion since it's nested one folder deeper
    template = template.replace("os.path.join(os.path.dirname(__file__), '..')", "os.path.join(os.path.dirname(__file__), '..', '..')")
    template = template.replace("from agents.mcp_server import MCPServer", f"from {agent_name}_server import {class_server_name}")
    
    return template


def get_server_template(agent_name: str) -> str:
    """Get the server.py template with placeholders replaced."""
    with open(os.path.join(AGENTS_DIR, 'mcp_server.py'), 'r', encoding='utf-8') as f:
        template = f.read()
    
    class_server_name = "".join([word.capitalize() for word in agent_name.split("_")]) + "Server"
    
    # Replace placeholders
    template = template.replace('MCPServer', class_server_name)
    template = template.replace("os.path.join(os.path.dirname(__file__), '..')", "os.path.join(os.path.dirname(__file__), '..', '..')")
    template = template.replace("from agents.mcp_tools import TOOL_REGISTRY", f"from {agent_name}_tools import TOOL_REGISTRY")
    
    return template


def get_tools_template() -> str:
    """Get a basic tools.py template with instructions."""
    return '''"""
MCP Tools — tool functions that return UI Primitives.

Generated by AstralBody Agent Creator.
"""
import os
import sys
from typing import Dict, Any, List

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from shared.primitives import (
    Text, Button, Card, Table, List_, Alert, ProgressBar, MetricCard,
    CodeBlock, Image, Grid, Tabs, Divider, Input, BarChart, LineChart,
    PieChart, PlotlyChart, Collapsible, Container,
    create_ui_response
)

# TODO: Add your tool functions here
# Each function should return a dict with _ui_components and _data keys
# Example:
# def example_tool(param1: str) -> Dict[str, Any]:
#     return create_ui_response([
#         Text(content=f"Result: {param1}", variant="body")
#     ])

# TODO: Register your tools in TOOL_REGISTRY
TOOL_REGISTRY = {
    # "example_tool": {
    #     "function": example_tool,
    #     "description": "Example tool description",
    #     "input_schema": {
    #         "type": "object",
    #         "properties": {
    #             "param1": {"type": "string", "description": "Example parameter"}
    #         },
    #         "required": ["param1"]
    #     }
    # }
}
'''


def generate_all_templates(agent_name: str, session: Dict[str, Any]) -> Dict[str, str]:
    """Generate all three template files."""
    return {
        "tools": get_tools_template(),
        "agent": get_agent_template(agent_name, session),
        "server": get_server_template(agent_name)
    }


if __name__ == "__main__":
    # Test the template generation
    test_session = {"name": "Test Agent"}
    templates = generate_all_templates("test_agent", test_session)
    print(f"Generated {len(templates)} templates")
    for key, content in templates.items():
        print(f"\n=== {key} === (first 200 chars)")
        print(content[:200])
