"""Filesystem layout for uploaded attachment blobs.

Layout (per data-model.md):

    {UPLOAD_ROOT}/{user_id}/{attachment_id}/{filename}

The directory-per-attachment layout makes deletion atomic and avoids
filename collisions when the same user uploads two files with the same name.
"""

from __future__ import annotations

import hashlib
import os
import shutil
from pathlib import Path
from typing import Iterable, Tuple


def get_upload_root() -> Path:
    """Resolve the on-disk upload root.

    Honors the ``ATTACHMENT_UPLOAD_ROOT`` env var; otherwise defaults to
    ``backend/tmp/`` relative to this module so behavior matches the
    legacy single-tenant layout.
    """
    override = os.getenv("ATTACHMENT_UPLOAD_ROOT")
    if override:
        return Path(override)
    backend_dir = Path(__file__).resolve().parents[2]  # backend/
    return backend_dir / "tmp"


def attachment_dir(user_id: str, attachment_id: str, root: Path | None = None) -> Path:
    """Return the directory holding a single attachment's blob."""
    base = root or get_upload_root()
    return base / user_id / attachment_id


def attachment_path(
    user_id: str,
    attachment_id: str,
    filename: str,
    root: Path | None = None,
) -> Path:
    """Return the absolute path of a single attachment's blob."""
    return attachment_dir(user_id, attachment_id, root) / filename


def write(
    user_id: str,
    attachment_id: str,
    filename: str,
    chunks: Iterable[bytes],
    *,
    max_bytes: int,
    root: Path | None = None,
) -> Tuple[Path, int, str]:
    """Stream *chunks* to disk under the canonical layout.

    Args:
        user_id: Owning Keycloak ``sub``.
        attachment_id: UUIDv4 generated by the caller.
        filename: Sanitized filename (caller is responsible for ``os.path.basename``).
        chunks: Iterable of byte chunks from the upload stream.
        max_bytes: Hard cap; raises :class:`ValueError` once the cumulative
            byte count exceeds this. Partial files are removed before the
            exception escapes.
        root: Override upload root (used by tests).

    Returns:
        ``(path, size_bytes, sha256_hex)``.

    Raises:
        ValueError: If the cumulative byte count exceeds ``max_bytes``.
    """
    target_dir = attachment_dir(user_id, attachment_id, root)
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / filename
    hasher = hashlib.sha256()
    total = 0
    try:
        with open(target, "wb") as fh:
            for chunk in chunks:
                if not chunk:
                    continue
                total += len(chunk)
                if total > max_bytes:
                    raise ValueError(
                        f"upload exceeded max_bytes={max_bytes} (got {total})"
                    )
                fh.write(chunk)
                hasher.update(chunk)
    except Exception:
        # Remove the partial blob and the now-empty attachment dir, then re-raise.
        try:
            if target.exists():
                target.unlink()
            if target_dir.exists() and not any(target_dir.iterdir()):
                target_dir.rmdir()
        except Exception:
            pass
        raise
    return target, total, hasher.hexdigest()


def read_path(user_id: str, attachment_id: str, filename: str, root: Path | None = None) -> Path:
    """Return the path to read an attachment, raising ``FileNotFoundError`` if missing."""
    p = attachment_path(user_id, attachment_id, filename, root)
    if not p.exists():
        raise FileNotFoundError(str(p))
    return p


def delete(user_id: str, attachment_id: str, root: Path | None = None) -> None:
    """Best-effort blob removal. Idempotent; missing dirs are not an error."""
    d = attachment_dir(user_id, attachment_id, root)
    if d.exists():
        shutil.rmtree(d, ignore_errors=True)


def delete_user(user_id: str, root: Path | None = None) -> None:
    """Recursively remove every blob owned by *user_id* (account-deletion path)."""
    base = (root or get_upload_root()) / user_id
    if base.exists():
        shutil.rmtree(base, ignore_errors=True)


__all__ = [
    "attachment_dir",
    "attachment_path",
    "delete",
    "delete_user",
    "get_upload_root",
    "read_path",
    "write",
]
